image: gradle:7.3.3-jdk17-alpine

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build:
  script:
    - ./gradlew build
    - ./gradlew AggregateJacocoReport
    # preserve coverage information in an easy-to-reach folder
    - mv build/reports/jacoco/aggregate/html ./coverage
    - mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
    - echo `sed -E 's/.*(Total[^%]+?%).*/\1/; s/<.*>//; s/Total/TestCoverage:/' coverage/index.html`
  artifacts:
    paths:
      - ./coverage
  coverage: /TestCoverage:(\d+)%/
